### ISSUE TITLE
[FEATURE REQUEST] Add a way to filter by Activity Type

### ISSUE THREAD

**Issue by kugiigi** [ernesst/ActivityTracker#15]
## Description
It would be good to have a way to filter activities by type.

**Comment by mymike00** [comment]
good news here, finally 😅
I managed to filter the activities, now I just need to make a cool UI :sunglasses:

**Comment by mymike00** [comment]
@kugiigi do you think filtering by one type at time is enough or would you prefer to be able to, for example, list Runs and BikeRides together?

**Comment by mymike00** [comment]
It could be like this. tap on the filter icon and the Sections appears, then tap which activity type you want to filter. tap again on filter icon to remove filters

![immagine](https://user-images.githubusercontent.com/28359593/64855413-191ae000-d620-11e9-8248-de1a14ef8625.png)

**Comment by kugiigi** [comment]
Yes, I think you screenshot shows a good layout for the filter 👍

**Comment by mymike00** [comment]
Thanks! an update with these changes will land soon

**Comment by mymike00** [comment]
version 0.14 is in the store!
