### ISSUE TITLE
Wish list (Import)

### ISSUE THREAD

**Issue by a-i-m-a-r** [ernesst/ActivityTracker#19]
Hi,
It would be great if the app could import gpx files. When I select a gpx file within the file manager, the content hub does not show the app.
My workaround is to create a dummy track, delete the newly created file and rename my gpx file (which I intend to import) to match with that dummy one.
The task would be easier if the names of the files created with the app show the actual data, rather than a numeric order I do not know how to interpret.
Thanks.
aimar

**Comment by mymike00** [comment]
It can import gpx tracks, you just need to open the app first and tap on import
btw, the file name is the time in unix format...

**Comment by a-i-m-a-r** [comment]
Got it. Thank you.
