### ISSUE TITLE
little change to german translation

### ISSUE THREAD

**Issue by gulton** [ernesst/ActivityTracker#20]
Hi, I have made a little change to the german translation. 
I hope is usefull for next version (I'm using Ubuntu Touch)

#: ../Tracker.qml:139
msgid "No, continue"
msgstr "Nein, fortsetzen"

#: ../Main.qml:528
msgid "close"
msgstr "Schließen"

**Comment by mymike00** [comment]
please, contribute translating those string on [weblate](https://hosted.weblate.org/projects/activity-tracker/translations/) that is how we manage translations, so next version I'll grab everything from there
