### ISSUE TITLE
Cannot be made to work in the backround?

### ISSUE THREAD

**Issue by Talkless** [ernesst/ActivityTracker#28]
I've enabled "Prevent app suspension" in UB Tweak Tool with expectation to make it work when inactive (switched application or locked screen), but I seems it doesn't. GPS icon goes off if I switch to other application, and track information is updated only when I activate ActivityTracker again (witch one huge jump in the track).

Workaround is to disable automatic screen locking, dim the backlight to conserve battery, and just keep it that way without locking screen and switching applications...

Any ideas why ActivityTracker can't work in "Prevent app suspension" mode, or am I misinterpreting what that checkbox means?

**Comment by ernesst** [comment]
Hello,

Thanks for your interest, unfortunately this limitation is OS related, please see this bug report : https://github.com/ubports/ubuntu-touch/issues/1067
I invite you to pursue the conversation there.

**Comment by Talkless** [comment]
Thanks for the link @ernesst !
