### ISSUE TITLE
German translation is so weird it makes app unusable

### ISSUE THREAD

**Issue by ruedigerkupper** [ernesst/ActivityTracker#29]
In the context of an activity tracker, "run" does certainly **not** mean „ausführen“ (= to execute, like in "run/execute code"). Translations in this app are so wrong one cannot even figure out basic usage.

I don't know who did the German translation, but he/she obviously was completely ignorant to what app this was. Where can I help correcting the translation?

**Comment by ruedigerkupper** [comment]
Actually it is better leaving an app untrunslated than translate it forcefully with a text book...

**Comment by ruedigerkupper** [comment]
The "run"/"ausführen" thing gets even worse, since there actually **is** an activity called „ausführen“ — it means "to take your pet for a walk". I was utterly confused why this should be the first choice in an activity tracker.

**Comment by ernesst** [comment]
Thanks for your feedback,
Could you please update the translation there : https://hosted.weblate.org/projects/activity-tracker/translations/de/

**Comment by ruedigerkupper** [comment]
Done.
