### ISSUE TITLE
port the app to focal

### ISSUE THREAD

**Issue by Danfro** [ernesst/ActivityTracker#39]
Hi @ernesst are you still actively maintaining the app? Any plans to port it to focal?

**Comment by boroli** [comment]
Is there any chance the beta binary version for focal can be downloaded/shared somewhere? Until now there's no version at all in the open-store. I would be keen to test it. I would say any version is better than no version :)

**Comment by Danfro** [comment]
@ernesst  and @mymike00 would you like me giving help maintaining the app? Or would you even like me to take over maintainer ship?
