### ISSUE TITLE
improve option to discard a track

### ISSUE THREAD

**Issue by Danfro** [ernesst/ActivityTracker#45]
There is currently no way to actually discard a track without saving.

- Press "start"
- select sport e.g. running
- start recording
- press stop
- you now have two options
   - no, keep recording -> obviously no stop
   - yes, stop -> goes to save screen
- in save screen we get two options
   - save -> that would be no discard
   - cancel -> goes back to recording 
- > that last dialog should have three options:
1. save
2. cancel and resume recording
3. cancel and discard track

**Comment by Danfro** [comment]
Sorry, just spotted that there is an option. The down arrow at the top left corner. But not sure if the dialog should also have that third option.

**Comment by mymike00** [comment]
Oh yeah, it is split over two different places. Maybe the down arrow should be hidden once the activity starts and all the action will be in the dialog shown by the stop button

**Comment by Danfro** [comment]
Yes, that seems to be more intuitive to me. Or it would at least need an icon that somehow indicates a cancel action.

**Comment by Danfro** [comment]
This issue has been fixed with the app that is now developed under https://github.com/Danfro/ActivityTracker.
