### ISSUE TITLE
OSM copyright notes barely visible

### ISSUE THREAD

**Issue by Danfro** [ernesst/ActivityTracker#53]
Currently the OSM copyright notes are barely visible since they are hidden behind the bottom controls.

Not sure if we should extend the map only to the top of the bottom controls. This way the copyright notes would be just above that. And I would think, we are not missing out too much of the map by attaching that to the top of the bottom controls.

**Comment by mymike00** [comment]
I really like that transparency effect on the map, so if it'd be possible to just move the copyright I'd be happy, otherwise as you said, just anchor the map to the top of the buttons

**Comment by Danfro** [comment]
I agree, it does look nice. :+1:  But it is there for a reason...
Hmm. There seem to be some option, but I am not sure for all of them how to apply them here.

1. OSM plugin
2. css
3. display another background

For 1. there is `osm.mapping.custom.mapcopyright` and `osm.mapping.custom.datacopyright`. But I don't see any position style option there, only a string change when using custom maps (which we are not doing).

For 2. when using a website map approach, there can be a css formated position as described [here](https://stackoverflow.com/questions/20981679/openlayers-map-change-position-of-attribution-in-javascript) and used in [uNav](https://github.com/costales/unav/blob/master/nav/css/ol.css). But this approach seem not easily implementable here since we don't display a website.

We could add a webview overlay with just the copyright string and format that. But seems to be a bit overkill.

For 3. we could display either a fixed part map or some nice activity tracker image background.

**Comment by Danfro** [comment]
This issue has been suficiently fixed with the app that is now developed under https://github.com/Danfro/ActivityTracker.
